# ACR Repository-Scoped Token for Gen AI Model Pulls
#
# Creates a repository-scoped token for the genai-model repository in ACR.
# This token is used by:
# - Nucleus server: Image existence checks via OCI registry API
# - Executors: Model downloads via crane CLI
#
# The token supports dual passwords for zero-downtime rotation:
# - password1: Current password (rotated by AcrCredentialRefresher)
# - password2: Previous password (kept for grace period)
#
# Note: Terraform creates the token infrastructure only (no passwords).
# Passwords are generated by the AcrCredentialRefresher:
# - Initial passwords: Generated by Helm post-install hook job
# - Rotation: Managed by CronJob (hourly)
# This approach keeps passwords out of Terraform state for better security.

# Scope map defining permissions for the genai-model repository
resource "azurerm_container_registry_scope_map" "genai_model_pull" {
  name                    = "genai-model-pull"
  container_registry_name = azurerm_container_registry.domino.name
  resource_group_name     = data.azurerm_resource_group.aks.name

  actions = [
    "repositories/genai-model/content/read",
    "repositories/genai-model/metadata/read",
  ]

  description = "Pull access to genai-model repository for Gen AI model operations"
}

# Repository-scoped token for Gen AI model pulls
resource "azurerm_container_registry_token" "genai_model_pull" {
  name                    = "domino-genai-model-pull"
  container_registry_name = azurerm_container_registry.domino.name
  resource_group_name     = data.azurerm_resource_group.aks.name
  scope_map_id            = azurerm_container_registry_scope_map.genai_model_pull.id
  enabled                 = true
}

# Note: No azurerm_container_registry_token_password resource
# Passwords are managed entirely by AcrCredentialRefresher to keep them out of Terraform state
